const path = {
  home: "/",
  map: "/map",
  login: "/login",
  register: "/register",
  place: "/place",
  explore: "/explore",
  promo: "/promo",
  saved: "/saved",
  search: "/search",
  review: "/review",
  message: "/message",
  messageUser: "/message/:id",
  placeDetail: "/place/:id",
  profile: "/profile",
  password: "/password",
  prefixRegion: "/search?regions",
  prefixCategory: "/search?categories",
  prefixPurpose: "/search?purposes",
  admin: {
    home: "/admin",
    place: "/admin/place",
    addPlace: "/admin/add-place",
    editPlace: "/admin/edit-place/:id",
    post: "/admin/post",
    promo: "/admin/promo",
    account: "/admin/account",
  },
  notFound: "*",
};

export default path;
